version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: vomblr/devops-for-programmers-project-74
    volumes:
    - ./app:/app
    command: bash -c 'npm test'

volumes:
  app:
